apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: rhdhpai802-9
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhdhpai802-9
  name: rhdhpai802-9
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
